pipeline:
  name: demo-pipeline
  identifier: demopipeline
  projectIdentifier: cicddemo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        build: <+input>
  stages:
    - stage:
        name: run build and test
        identifier: run_build_and_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: run unit test
                  identifier: Run_1
                  spec:
                    connectorRef: <+input>
                    image: maven:3.8.6-openjdk-11
                    shell: Sh
                    command: mvn test
              - step:
                  type: Run
                  name: build project
                  identifier: build_project
                  spec:
                    connectorRef: <+input>
                    image: maven:3.8.6-openjdk-11
                    shell: Sh
                    command: mvn clean install
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to Docker Registry
                  identifier: Build_and_Push_to_Docker_Registry
                  spec:
                    connectorRef: <+input>
                    repo: <+input>
                    tags:
                      - "1.0"
